site_name: Memor 

nav:
  - Home: index.md

  - Module overview: 
      - moduleoverview/index.md
      - Memor: moduleoverview/memor.md
      - Scenes: moduleoverview/scenes.md
      - ECS: moduleoverview/ecs.md
      - Math: moduleoverview/math.md
      - Sprites and Animations: moduleoverview/spritesandanimations.md
      - Sounds: moduleoverview/sounds.md
      - Collision and Physics: moduleoverview/collisionandphysics.md
      - Utils: moduleoverview/utils.md

  - Devlog:
    - devlog/index.md




theme:
  name: material
  features:
    - navigation.indexes 
  highlightjs: true
  font:
    text: DM Sans
    code: DM Mono Medium
  palette:
    scheme: slate
    primary: black
    accent: teal



plugins:
  - blog:
      enabled: true
      blog_dir: devlog
      blog_toc: true
  - search


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
